version: '3'

services:
  redis:
    image: redis
    ports:
      - '6380:6379'

  postrgeSQL:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    container_name: postrgeSQL
    ports:
      - '5404:5432'
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 10s
      timeout: 5s
      retries: 5

  django:
    build: .
    tty: true
    command: sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/django
    ports:
      - '8000:8000'
    depends_on:
      postrgeSQL:
        condition: service_healthy

  celery:
    build: .
    tty: true
    command: celery -A config worker -l INFO
    depends_on:
      - redis
      - django

  celery_beat:
    build: .
    restart: on-failure
    tty: true
    command: celery -A config beat -l INFO -S django
    depends_on:
      - redis
      - django

volumes:
  pg_data: