# Generated by Django 4.2.7 on 2024-01-06 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('place',
                 models.CharField(blank=True,
                                  max_length=200,
                                  null=True,
                                  verbose_name='место, в котором '
                                               'необходимо '
                                               'выполнять привычку')),
                ('time',
                 models.DateTimeField(blank=True,
                                      null=True,
                                      verbose_name='время, когда'
                                                   'необходимо'
                                                   'выполнять привычку')),
                ('action',
                 models.CharField(blank=True,
                                  choices=[('walk', 'Гулять '
                                                    'на свежем воздухе'),
                                           ('drink', 'Пить больше воды'),
                                           ('good_mood', 'Быть всегда'
                                                         ' в хорошем '
                                                         'настроении')],
                                  max_length=200, null=True,
                                  verbose_name='действие')),
                ('is_nice',
                 models.BooleanField(default=False,
                                     verbose_name='признак '
                                                  'приятной '
                                                  'привычки')),
                ('period',
                 models.CharField(blank=True,
                                  choices=[('daily', 'Ежедневная'),
                                           ('weekly', 'Раз в неделю')],
                                  max_length=50, null=True,
                                  verbose_name='периодичность')),
                ('lead_time',
                 models.IntegerField(blank=True,
                                     null=True,
                                     verbose_name='время на выполнение')),
                ('reward',
                 models.CharField(blank=True,
                                  max_length=100,
                                  null=True,
                                  verbose_name='вознаграждение')),
                ('is_public',
                 models.BooleanField(default=False,
                                     verbose_name='признак публичности')),
                ('habits',
                 models.ForeignKey(blank=True,
                                   null=True,
                                   on_delete=django.db.models.deletion.CASCADE,
                                   to='habits.habit',
                                   verbose_name='связанная привычка')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
